DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email TEXT NOT NULL,
    password TEXT NOT NULL,
    name TEXT,
    photo_url TEXT,
    photo_id TEXT,
    bio TEXT,
    sport BOOLEAN,
    trad BOOLEAN,
    min_grade INTEGER,
    max_grade INTEGER,
    location_srid GEOMETRY,
    latitude FLOAT,
    longitude FLOAT,
    address TEXT,
    radius INTEGER,
    date_created TIMESTAMP DEFAULT now() NOT NULL
);