DROP TABLE IF EXISTS users;

DROP TYPE IF EXISTS CLIMBING_STYLE;

DROP TYPE IF EXISTS GRADE;

CREATE TYPE CLIMBING_STYLE AS ENUM ('sport', 'trad');

CREATE TYPE GRADE AS ENUM ('5.0', '5.1', '5.2', '5.3', '5.4', '5.5', '5.6', '5.7', '5.8', '5.9', '5.10', '5.11-', '5.11+', '5.12-', '5.12+', '5.13-', '5.13+', '5.14-', '5.14+', '5.15');

CREATE TABLE users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email TEXT NOT NULL,
    password TEXT NOT NULL,
    name TEXT,
    photo_url TEXT,
    photo_id INTEGER,
    bio TEXT,
    style CLIMBING_STYLE[],
    grades_min GRADE,
    grades_max GRADE,
    location POINT,
    radius INTEGER,
    date_created TIMESTAMP DEFAULT now() NOT NULL
);