DROP TABLE IF EXISTS users;

DROP TYPE IF EXISTS CLIMBING_STYLE;

CREATE TYPE CLIMBING_STYLE AS ENUM ('sport', 'trad');

CREATE TABLE users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email TEXT NOT NULL,
    password TEXT NOT NULL,
    name TEXT,
    photo_url TEXT,
    photo_id TEXT,
    bio TEXT,
    styles CLIMBING_STYLE[],
    min_grade INTEGER,
    max_grade INTEGER,
    location GEOMETRY,
    radius INTEGER,
    date_created TIMESTAMP DEFAULT now() NOT NULL
);